// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.3.0
// - protoc             v4.24.0
// source: kratosworld/v1/kratosworld.proto

package v1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

const (
	KratosWorldService_SayHello_FullMethodName = "/kratosworld.v1.KratosWorldService/SayHello"
)

// KratosWorldServiceClient is the client API for KratosWorldService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type KratosWorldServiceClient interface {
	// Sends a greeting
	SayHello(ctx context.Context, in *HelloRequest, opts ...grpc.CallOption) (*HelloReply, error)
}

type kratosWorldServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewKratosWorldServiceClient(cc grpc.ClientConnInterface) KratosWorldServiceClient {
	return &kratosWorldServiceClient{cc}
}

func (c *kratosWorldServiceClient) SayHello(ctx context.Context, in *HelloRequest, opts ...grpc.CallOption) (*HelloReply, error) {
	out := new(HelloReply)
	err := c.cc.Invoke(ctx, KratosWorldService_SayHello_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// KratosWorldServiceServer is the server API for KratosWorldService service.
// All implementations must embed UnimplementedKratosWorldServiceServer
// for forward compatibility
type KratosWorldServiceServer interface {
	// Sends a greeting
	SayHello(context.Context, *HelloRequest) (*HelloReply, error)
	mustEmbedUnimplementedKratosWorldServiceServer()
}

// UnimplementedKratosWorldServiceServer must be embedded to have forward compatible implementations.
type UnimplementedKratosWorldServiceServer struct {
}

func (UnimplementedKratosWorldServiceServer) SayHello(context.Context, *HelloRequest) (*HelloReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SayHello not implemented")
}
func (UnimplementedKratosWorldServiceServer) mustEmbedUnimplementedKratosWorldServiceServer() {}

// UnsafeKratosWorldServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to KratosWorldServiceServer will
// result in compilation errors.
type UnsafeKratosWorldServiceServer interface {
	mustEmbedUnimplementedKratosWorldServiceServer()
}

func RegisterKratosWorldServiceServer(s grpc.ServiceRegistrar, srv KratosWorldServiceServer) {
	s.RegisterService(&KratosWorldService_ServiceDesc, srv)
}

func _KratosWorldService_SayHello_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(HelloRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(KratosWorldServiceServer).SayHello(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: KratosWorldService_SayHello_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(KratosWorldServiceServer).SayHello(ctx, req.(*HelloRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// KratosWorldService_ServiceDesc is the grpc.ServiceDesc for KratosWorldService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var KratosWorldService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "kratosworld.v1.KratosWorldService",
	HandlerType: (*KratosWorldServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "SayHello",
			Handler:    _KratosWorldService_SayHello_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "kratosworld/v1/kratosworld.proto",
}
